### ISSUE TITLE
support ROS2?

### ISSUE THREAD

**Issue by the-sword** [ZVISION-lidar/zvision_ros_driver#1]
Hi, thanks for your great work.
I would like to ask if there is a version that supports ROS2?

**Comment by Chenskkk** [comment]
> Hi, thanks for your great work. I would like to ask if there is a version that supports ROS2?

Hi, please switch to ros2-foxy branch.

**Comment by the-sword** [comment]
@Chenskkk Sorry for not switching. Thanks.
